var limitnum = 1000;
var map = {
	LEAR_HIS: {
		table: '"ZSCH_ODATA"."ZTAB_LMS_LEARNING_HIS"',
		sql: 'SELECT distinct TAB_LASTMODIFIED_TIME_UTC AS TAB_LASTMODIFIED_TIME,STUD_ID,ACTIVE_USER,FIRSTNAME,LASTNAME,MIDDLENAME,CPNTID,CPNTTYPEID,TYPE,REVDATE,REVNUM,CPNTDESC,SCHEDID,COMPLDATE,GRADE,COMPLSTATID,COMPLSTATDESC,TOTALHRS,CREDITHRS,CONTACTHRS,CPEHRS,TUITION,CURRENCYSYMBOL,CURRENCYCODE,INSTNAME,ESUSERNAME,LSTTMSP,ESIGMEANINGCODE,EVENTCOMMENTS FROM "ZSCH_ODATA"."ZTAB_LMS_LEARNING_HIS" ',
		where: 'WHERE TO_VARCHAR(TO_SECONDDATE("TAB_LASTMODIFIED_TIME_UTC", \'YYYY-MM-DD HH24:MI:SS\'),\'YYYY-MM-DD HH24:MI:SS\') >=',
		orderby: 'ORDER BY STUD_ID DESC'
	}

};